# Generated by Django 3.2.7 on 2021-10-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211023_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('number', models.IntegerField(default='', max_length=10)),
            ],
        ),
    ]
